import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import Titus from "/public/MyImages/Titus.jpeg";
import ty from "/public/MyImages/Titus.png";
import ty2 from "/public/MyImages/ty3.jpeg";
import design from "/public/MyImages/design.png";
import code from "/public/MyImages/code.png";
import web1 from "/public/MyImages/web2.png";
import web2 from "/public/MyImages/web3.png";
import web3 from "/public/MyImages/web4.png";
import web4 from "/public/MyImages/web5.png";
import web5 from "/public/MyImages/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>TFT Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-black px-10 md:text-center md:px20 lg:px-40 ">
        <section className=" min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons  dark:text-cyan-500">
              DevelopedByMe
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-cyan-500"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py2 bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 text-transparent bg-clip-text font-medium md:text-6xl;">
              Titus Faulkner Tull
            </h2>
            <h3 className=" text-2xl py-2 md:text-3xl  dark:text-cyan-500">
              Web Designer
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl">
              My dream is to be responsible for planning and developing software
              solutions and web applications, while supporting and maintaining a
              companys websites and digital products.
            </p>
          </div>
          <div className=" text-6xl flex justify-center gap-16 py3 text-cyan-700 ">
            <AiFillTwitterCircle className="text-blue-500" />
            <AiFillYoutube className="text-red-500" />
            <AiFillLinkedin className="text-blue-600" />
          </div>
          <div className=" relative w-fit h-fit mx-auto bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 rounded-full">
            <Image
              className="mx-auto scale-95 rounded-full w-auto h-auto"
              src={ty2}
              alt={""}
            />
          </div>
        </section>
        <section>
          <div className=" text-center">
            <h3 className="text-3xl py-1  dark:text-cyan-500">
              Service I Provide
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              <span className="bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 text-transparent bg-clip-text">
                Interractive
              </span>{" "}
              and{" "}
              <span className="bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 text-transparent bg-clip-text">
                mobile{" "}
              </span>{" "}
              ready websites.
            </p>
          </div>
          <div className="lg:flex gap-10 justify-between items-center   ">
            <div className="text-center shadow-2xl shadow-cyan-600/60 p-10 rounded-xl my-10 ">
              <Image
                className="mx-auto max-w-lg h-auto "
                src={design}
                width={100}
                height={100}
                alt={""}
              />
              <h3 className=" dark:text-cyan-500 text-lg font-medium pt-8 pb-2">
                Stunning Simplistic Designs
              </h3>
              <p className=" py-2 text-gray-800">
                Elegant designs suited for most needs, simple yet stunning
              </p>
              <h4 className="py-4 text-cyan-600">Design Tools I love To Use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Spline</p>
              <p className="text-gray-800 py-1">Photo Editor</p>
            </div>

            <div className=" text-center shadow-2xl shadow-cyan-600/60 p-10 rounded-xl my-10">
              <Image
                className="mx-auto max-w-lg h-auto lg:h-100-w-100"
                src={ty}
                width={135}
                height={100}
                alt={""}
              />
              <h3 className=" dark:text-cyan-500 text-lg font-medium pt-8 pb-2">
                Peronalized to the Tee
              </h3>
              <p className=" py-2 text-gray-800">Go the extra mile</p>
              <h4 className="py-4 text-cyan-600">
                Everything I work on is a passion piece to me
              </h4>
              <p className=" dark:text-cyan-500">Eat</p>
              <p className=" dark:text-cyan-500">Sleep</p>
              <p className=" dark:text-cyan-500">Code</p>
            </div>
            <div className=" text-center shadow-2xl shadow-cyan-600/60 p-10 rounded-xl my-10">
              <Image
                className="mx-auto max-w-lg h-auto"
                src={code}
                width={100}
                height={100}
                alt={""}
              />
              <h3 className=" dark:text-cyan-500 text-lg font-medium pt-8 pb-2">
                Pages coded in the latest frameworks
              </h3>
              <p className=" py-2 text-gray-800">Fast Responsive Modern</p>
              <h4 className="py-4 text-cyan-600"> Fast Content</h4>
              <p className="text-gray-800 py-1">
                <span className="bg-gradient-to-t  from-cyan-600 via-cyan-700 to-teal-600 text-transparent bg-clip-text">
                  tailwindCSS
                </span>{" "}
              </p>
              <p className="text-gray-800 py-1">
                React
                <span className="bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 text-transparent bg-clip-text">
                  Js
                </span>
              </p>
              <p className="text-gray-800 py-1">
                Node
                <span className="bg-gradient-to-t  from-cyan-500 via-cyan-700 to-teal-500 text-transparent bg-clip-text">
                  Js
                </span>{" "}
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className=" flex flex-col gap-10 py-5 lg:flex-row space-between justify-evenly ">
            <div className=" basis-1/2 flex-1 ">
              <Image
                src={web5}
                className=" rounded-2xl object-contain  "
                width={400}
                height={400}
                alt={""}
              />
            </div>
            <div className=" basis-1/2 flex-1 ">
              <Image
                src={web2}
                className=" rounded-2xl object-contain"
                width={400}
                height={200}
                alt={""}
              />
            </div>
            <div className=" basis-1/2 flex-1 ">
              <Image
                src={web4}
                className=" rounded-2xl object-contain  "
                width={400}
                alt={""}
              />
            </div>
            <div className=" basis-1/2 flex-1 ">
              <Image
                src={web3}
                className="  rounded-2xl object-contain  "
                width={400}
                alt={""}
              />
            </div>
          </div>
          <div className=" fill-current ">
            <p className=" ml-0 mb-10 bg-gradient-to-r from-cyan-500 to-teal-500 text-gray-800 p-2 rounded-md ml-8 mb-0 text-center shadow-2xl ">
              “It does not matter how slowly you go as long as you do not stop.”
              “Never give up, for that is just the place and time that the tide
              will turn.”
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
